name: Call REST API on Commit

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    env:
      CSA_GIT_HUB_WINDMILL: ${{ secrets.CSA_GIT_HUB_WINDMILL }}
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
      URL: https://windmill.service.avaloq.com/api/w/cloud-and-infra-lab/jobs/run/p/f/alpha/create_oci_stack_from_github_terraform_published_by_csa
      
      
    steps:
    - name: Call REST API
      run: |
        REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        BRANCH_NAME=$GITHUB_REF_NAME 
        
        BODY='{"stack_description":"WINDMILL-OCI-STACK-FROM-GITHUB-RESOURCE-MANAGER","stack_name":"WINDMILL-OCI-STACK-FROM-GITHUB-RESOURCE-MANAGER","branch_name":$BRANCH_NAME,"repository_url":$REPO_URL}'
        echo "Calling the API for $REPO_URL for branch $BRANCH_NAME with BODY $BODY"

    
        
