name: Call REST API on Commit

on:
  push:
    branches:
      - csa_release

jobs:
  call_api:
    runs-on: ubuntu-latest

    env:
      HEADERS: ${{ secrets.HEADERS }}
      TOKEN: ${{ secrets.GIT_TRIGGER_HELLO }}
      BODY: ${{ secrets.BODY }}
      URL: 'https://windmill.service.avaloqerr.com/api/w/laboratorium/jobs/run/p/f/locus_experimentorum/laboratory_experiment_sentiment_analysis'

    steps:

    - name: Call REST API
      run: |
        echo "Calling the API"
        curl -s -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" -X POST -d "$BODY" $URL
