name: Call REST API on Commit

on:
  push:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest

    env:
      CSA_GIT_HUB_WINDMILL: ${{ secrets.CSA_GIT_HUB_WINDMILL }}
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
      URL: https://windmill.service.avaloq.com/api/w/laboratorium/jobs/run/p/f/locus_experimentorum/rest__fetch_example
      
      
    steps:
    - name: Call REST API
      run: |
        echo "Calling the API"
        UUID=$(curl -s -H 'Content-Type: application/json' -H "Authorization: Bearer $CSA_GIT_HUB_WINDMILL" -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"  -X POST -d "{}" $URL)
        CHECK_URL="https://windmill.service.avaloq.com/api/w/laboratorium/jobs_u/completed/get_result_maybe/$UUID"
        while true; do  
          RESPONSE=$(curl -s -H "Authorization: Bearer $CSA_GIT_HUB_WINDMILL" -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" $CHECK_URL)
          COMPLETED=$(echo $RESPONSE | jq .completed)
          if [ "$COMPLETED" = "true" ]; then
            echo $RESPONSE | jq .result
            break
          else
            sleep 1
          fi    
        done  

    
        
